### ISSUE TITLE
Resource cache is not cleared on different user login

### ISSUE THREAD

**Issue by raghuvaran** [salvoravida/react-adal#68]
`react-adal` library caches a delegated token by resource name (`adal.access.token.keyhttps://organization.onmicrosoft.com/hello-world-app/`). Usually when using `adalFetch` the library acquires new resource/delegated token when it doesn't find one in the storage.

 When a different user logins in with same state i.e. by going back to the Microsoft login page using browser back button from a logged in app, adal library caches the new "id_token" and "access_token", but doesn't update the resource/delegated token. On every new request adal (the `acquireToken` method) is using the token from cache (which in this case is stale token).

**Comment by salvoravida** [comment]
@raghuvaran

Hi, thank you for your pr.
i suggest to try first to send a pr to official adal.js library (that react-adal use)
https://github.com/AzureAD/azure-activedirectory-library-for-js

otherwise you can check this branch
https://github.com/salvoravida/react-adal/tree/dev-invalidation

and if all is ok, we can release a new react-adal version with this mod
while waiting for official lib integration

**Comment by salvoravida** [comment]
@raghuvaran thanks for suggestion. it should be fixed on v0.5.0 

let me know your feedback!
