### ISSUE TITLE
How to use it in SSR project with Next.js ?

### ISSUE THREAD

**Issue by saostad** [salvoravida/react-adal#76]
first of all thanks for the library.
I am planning to use this library to my Next.js app but I couldn't set it up based on current documentation.
can you please provide instruction on how to set up a simple server-side rendered app?
and also how to set up storage location? because as far as I know it should be on the cookie but cookie is not an option in adal.

**Comment by saostad** [comment]
I finally find the solution and made a repository for others who are trying to do the same.

https://github.com/saostad/nextjs-office365-auth

**Comment by BlackFenix2** [comment]
ay yo @saostad , i checked out your repo and used it myself on a Gatsby project. the issue is if i use sessionStorage my site flashed 3 times before the login/callback functions finish executing.

i had to somewhat rewrite the runWithAdal function as a wrapperComponent to accomdiate SSR/Static site generating frameworks such as gatsby and nextjs. I can make a PR to Add an "AdalProvider" HOC. ill reference the PR once i create it.

```js
const RunWithAdal = ({ context, children }) => {
  const isLoggedIn = () => {
    // it must run in iframe too for refreshToken (parsing hash and get token)
    context.handleWindowCallback();

    // prevent iframe double app !!!
    if (window === window.parent) {
      if (!context.isCallback(window.location.hash)) {
        if (
          !context.getCachedToken(context.config.clientId) ||
          !context.getCachedUser()
        ) {
          context.login();
        } else {
          return true;
        }
      }
    }
    return false;
  };

  // rednder children if user is logged in
  return !isLoggedIn() ? <div /> : children;
};
```

usage as so:

```js
const Wrapper = ({ element }) => (
  <Provider>
    <RunWithAdal context={authContext}>{element}</RunWithAdal>
  </Provider>
);

export default Wrapper;
```

**Comment by BlackFenix2** [comment]
i made the PR here: https://github.com/salvoravida/react-adal/pull/80

changed a lot more than anticipated. but the local tests work.

**Comment by salvoravida** [comment]
duplicatied #67
