### ISSUE TITLE
A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`

### ISSUE THREAD

**Issue by adlele** [salvoravida/react-adal#97]
Is there a plan to manage samesite cookies

**Comment by AndrewCraswell** [comment]
Can't speak to this library, since it's based on ADAL which is essentially deprecated, but the issue is known and the new MSAL library has an issue logged for it:
https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1037

Seems it's something that may be resolved upstream from both ADAL and MSAL, so my assumption would be when fixed, it should apply to both libraries without changes needed.

**Comment by salvoravida** [comment]
it's a server side problem not client side
https://devblogs.microsoft.com/aspnet/upcoming-samesite-cookie-changes-in-asp-net-and-asp-net-core/
